# Download script file from GitHub
init:
  ps: |
        Get-Date
        $ErrorActionPreference = "Stop"
install:
  ps: |
        Import-Module '.\scripts\appveyor-tool.ps1'
        Bootstrap
# Adapt as necessary starting from here

environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    _R_CHECK_SYSTEM_CLOCK_: FALSE
    GITHUB_PAT:
      secure: c5a408564ccc24b831c927a6212c75bcaa4a8eb7

  matrix:
  - R_VERSION: 3.4.4
    R_ARCH: x64
    GCC_PATH: mingw_64